src/Server.php, src/ServerInterface.php
Removed the use of the special `@event` annotation to ease the use of the lib with annotation library, in particular Doctrine annotations
see https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Common/Annotations/AnnotationReader.php#L55 for the list of ignored annotation
=> Annotations fix

.travis.yml, composer.json, src/Server.php
Because *why not*… :-)
Now more seriously: This project is a low level lib that is used as a building block for quite a few higher level abstractions on top of it. As such, compatibility (even with significantly outdated versions) is a major concern to me.
Note that I'm not suggesting putting *significant amount* of work into this. The patch is already here and, personally, I see little harm in supporting this.
Also note that I'm not suggesting we need to keep support indefinitely. Should this ever turn out to be a burden in the future, e.g. because we actually *require* any new language features or some external lib, then I'm all for dropping support again.
=> [RFC] Improve compatibility with legacy versions

README.md, composer.json, src/Connection.php, src/ConnectionInterface.php
Make sure the `ConnectionInterface` actually extends the `DuplexStreamInterface` introduced with react/stream v0.4.2. Thus, the main difference here is this:
```diff
-interface ConnectionInterface extends ReadableStreamInterface, WritableStreamInterface
+interface ConnectionInterface extends DuplexStreamInterface
```
Note that this is not a BC break because the `DuplexStreamInterface` actually extends both `ReadableStreamInterface` and `WritableStreamInterface`.
Also update the documentation to emphasize this is the main interface that is to be used to represent incoming connections.
=> ConnectionInterface should extend DuplexStreamInterface + documentation

src/Connection.php, tests/ConnectionTest.php, tests/ServerTest.php, tests/TestCase.php
Added some additional test cases to verify we can use the normal stream handler which processes any stream filters and handles any errors.
It looks like the original motivation for using raw stream handlers was that some Autobahn tests failed "very oddly" (https://github.com/reactphp/react/pull/240). I assume this might have been fixed in the meantime, possibly as part of https://github.com/reactphp/stream/pull/20.
=> Improve test suite and switch to normal stream handler

.travis.yml, README.md, composer.json, tests/FunctionalServerTest.php
This simple PR aims to add a functional integration test (which also happens to be a prerequisite for implementing #24).
Unfortunately, this simple change introduces an indirect cyclic dependency between `socket -> socket-client -> dns -> socket` which causes the test setup to fail. I'm opening this PR in the hope to propose and discuss a possible solution.
=> Add functional integration tests

README.md, src/Server.php, tests/FunctionalServerTest.php
=> Support socket context options passed to Server

README.md, src/SecureServer.php, src/Server.php, src/ServerInterface.php, tests/SecureServerTest.php, tests/ServerTest.php, tests/Stub/ServerStub.php
This very simple PR renames the `shutdown()` method to `close()` in order to achieve consistency throughout React's components.
The term "shutdown" is actually an implementation detail of sockets and does not really apply to closing a server socket.
FWIW, Node also uses "close".
=> Rename shutdown() to close() for consistency throughout React

README.md, src/Server.php, tests/FunctionalServerTest.php
Listening on a hostname such as `example.com` or `localhost` is a blocking operation. This simple PR enforces the host to consists of an IP address.
Fixes / closes #7
Refs / builds on top of #65
=> Reject listening on hostnames and document valid URIs

README.md, examples/01-echo.php, examples/02-chat-server.php, examples/03-benchmark.php, src/SecureServer.php, src/Server.php, src/ServerInterface.php, tests/FunctionalSecureServerTest.php, tests/FunctionalServerTest.php, tests/SecureServerTest.php, tests/ServerTest.php, tests/Stub/ServerStub.php
The `getPort()` currently only returns the "port" part and explicitly omits the listening IP. This has been documented as of v0.4.4 and has in fact been like this ever since this method has been added.
This PR replaced this method with a `getAddress()` method that it returns the full remote address, i.e. IP and port.
```diff
- echo $server->getPort();
- 8000
+ echo $server->getAddress();
+ 192.168.0.12:8000
```
This is obviously a BC break, so I've made sure to add documentation on how to get only the port from the full address with a one-liner.
Empirical evidence seems to suggest the old `getPort()` method isn't used *that* much and is mostly used in a context where the full URI likely makes more sense anyway. For TCP/IP based servers, the full URI contains the port and with the above …
=> Replace getPort() with getAddress()

README.md, src/Connection.php, src/ConnectionInterface.php, tests/FunctionalServerTest.php
This PR implements a simple `getLocalAddress()` method which complements the existing `getRemoteAddress()` method already present on the `ConnectionInterface`.
This can be useful if your `Server` instance is listening on multiple interfaces (e.g. using the address `0.0.0.0`). You can use this method to find out which interface actually accepted this connection (such as a public or local interface).
Adding this method is a new feature from a consumer perspective. Marking this as "BC break" in case any consumers of this package *implement* this interface (this should not affect most users, aka. *normal* usage).
Refs reactphp/react#199 and #65
=> Add getLocalAddress() method

README.md, src/SecureServer.php, tests/SecureServerTest.php
Make sure underlying plaintext TCP/IP socket server exposes the correct
context options to the secure TLS socket server.
Marking this as a bug, but it is very unlikely to have caused any issues in real-world code, as this does not occur if one follows the existing documentation.
This could only really happen if one were to extend the `Server` class and returned custom connection instances that implement the `ConnectionInterface` but do not extend the `Stream class`.
Refs https://github.com/reactphp/socket-client/pull/73
=> Documentation and tests for exposing secure context options

README.md, src/SecureServer.php, src/Server.php, tests/FunctionalSecureServerTest.php, tests/FunctionalServerTest.php, tests/SecureServerTest.php
Interfering with this (previously public) property could introduce some very subtle bugs, so it's best to simply avoid exposing it.
Empirical evidence seems to suggest this isn't used much outside of this package anyway.
Inside this package, we can safely replace all references to it with references to child sockets created upon connection.
Also, the `SecureServer` now supports any underlying `ServerInterface` (advanced usage) and no longer relies on a concrete implementation.
Builds on top of #69
=> Do not expose $master property and accept any ServerInterface for SecureServer

README.md, src/SecureServer.php, src/Server.php, tests/SecureServerTest.php, tests/ServerTest.php
Classes should be used via composition rather than extension.
This reduces our API footprint and avoids future BC breaks by avoiding
exposing its internal assumptions.
Builds on top of #70
=> Mark Server and SecureServer as final and mark internal connection handler as internal

README.md, src/ConnectionException.php, src/Server.php, tests/FunctionalServerTest.php, tests/ServerTest.php
This simple PR replaces the undocumented `ConnectionException` with a generic `RuntimeException`.
Also adds some documentation for when this occurs and is now in line with other exceptions described in #60 and #61.
Extending the `ErrorException` doesn't really make any sense, because we never actually supported any of its properties.
This change introduces a small BC break, but I figured it's worth it because it reduces the API footprint further (refs #71 and #70) and makes sure our exception usage is consistent across this project.
Also closes #56 while we're at it :shipit:
=> Replace custom ConnectionException with generic RuntimeException

README.md, composer.json, src/ConnectionInterface.php
This component is in fact already compatible with v0.4, the new v0.5 and the upcoming v0.6, see also https://github.com/reactphp/stream/issues/67.
=> Forward compatibility with Stream v0.5 and upcoming v0.6

composer.json, tests/FunctionalSecureServerTest.php, tests/FunctionalServerTest.php
Also refs #79 because the old SocketClient does not support the newer Streams API.
=> Simplify tests by updating SocketClient to v0.6

README.md, src/SecureServer.php, src/Server.php, src/ServerInterface.php, tests/FunctionalServerTest.php, tests/SecureServerTest.php, tests/ServerTest.php
The `pause()` and `resume()` methods can be used to limit the number of active connections.
This can be used to stop accepting incoming connections once a certain limit is reached, so that the operating system backlog is responsible for managing pending connections.
I've prepared a follow-up PR for adds a simple API to control the maximum number of active connections.
=> Add pause() and resume() methods to limit active connections

src/Connection.php, tests/IntegrationTest.php
HHVM raises a PHP warning when trying to shut down a socket that is already closing because the other side closed the connection. This does not happen for any other PHP version, so simply ignore this error as part of the shut down procedure.
Refs https://github.com/clue/php-http-proxy-react/pull/9 and https://travis-ci.org/clue/php-http-proxy-react/jobs/220595506
=> Ignore HHVM errors when closing connection that is already closing

src/TcpConnector.php
Noticed this tweet by @nrk: https://twitter.com/JoL1hAHN/status/854332152791654401?s=09
This currently only affects PHP 7.0.18 and 7.1.4: https://3v4l.org/ivR7T
Apparently introduced via https://bugs.php.net/bug.php?id=74216
This issue has already been reported upstream: https://bugs.php.net/bug.php?id=74429
=> Work around latest PHP 7.0.18 and 7.1.4 no longer accepting full URIs

README.md, examples/01-echo.php, examples/02-chat-server.php, examples/03-benchmark.php, src/ConnectionInterface.php, src/SecureServer.php, src/TcpServer.php, tests/FunctionalSecureServerTest.php, tests/FunctionalTcpServerTest.php, tests/LimitingServerTest.php, tests/SecureIntegrationTest.php, tests/SecureServerTest.php, tests/TcpConnectorTest.php, tests/TcpServerTest.php
This simple PR renames the `Server` class to `TcpServer`.
A follow-up PR will introduce a new `Server` class which acts as a facade for the existing server classes. This class allows to start a `TcpServer` as-is and will prepare the code for the upcoming Unix domain socket server (#25) and upcoming `SecureServer` with auto-generated certificates (#95). This will work very similar to how the `Connector` class is a facade for the client side connector classes.
In other words, the follow-up PR will restore compatibility with consumer code so this does in fact not result in a BC break for most users.
=> Rename Server to TcpServer

README.md, examples/01-echo.php, examples/02-chat-server.php, examples/03-benchmark.php, src/Server.php, src/TcpServer.php, tests/ServerTest.php
This is a follow-up PR to #96 which introduces a new Server class which acts as a facade for the existing server classes. This class allows to start a TcpServer and SecureServer as-is and will prepare the code for the upcoming Unix domain socket server (#25) and upcoming SecureServer with auto-generated certificates (#95). This works very similar to how the Connector class is a facade for the client side connector classes.
This also *fixes* the intentional BC break introduced in #96 so that consumer code does not have to be updated.
Builds on top of #96
=> Add Server facade for existing server classes

README.md, examples/01-echo.php, examples/02-chat-server.php, src/Connection.php, src/ConnectionInterface.php, src/SecureServer.php, src/ServerInterface.php, src/StreamEncryption.php, src/TcpServer.php, tests/FunctionalSecureServerTest.php, tests/LimitingServerTest.php, tests/ServerTest.php, tests/TcpConnectorTest.php
This simple PR ensures that all addresses are now returned as URIs that include the URI scheme. This eases checking whether the connection is encrypted (`tls://` scheme) and also eases parsing individual URI components as passing the string to `parse_url()` no longer requires an explicit scheme prefix.
This is in fact a BC break for anybody who previously relied on explicitly prefixing this, but actually eases parsing:
```diff
- $parts = parse_url('tcp://' . $conn->getRemoteAddress());
+ $parts = parse_url($conn->getRemoteAddress());
```
=> All addresses are now URIs that include the URI scheme

README.md, composer.json, src/Connection.php, src/SecureConnector.php, src/SecureServer.php, src/StreamEncryption.php, tests/FunctionalSecureServerTest.php, tests/IntegrationTest.php, tests/SecureIntegrationTest.php, tests/TcpServerTest.php, tests/TestCase.php
This is not a BC break because it only affects the internal `Connection` class (and its tests) and does not affect the public `ConnectionInterface`.
=> Forward compatibility with Stream v1.0 and v0.7

README.md, src/Connection.php, src/ConnectionInterface.php, src/UnixConnector.php, tests/UnixConnectorTest.php
Resolves / closes #92
Supersedes / closes #93
Builds on top of #98
=> Fix unix:// addresses for Unix domain socket (UDS) paths

README.md, composer.json, tests/FunctionalConnectorTest.php
The `Connector` (and underlying `DnsConnector`) now honors the hosts file on all platforms by default. This means that you can now connect to `localhost` etc..
Resolves / closes #88
Refs https://github.com/reactphp/dns/pull/75
=> Update DNS dependency to support hosts file on all platforms

src/TcpConnector.php
At first, some background on this. I have a long-running script that maintains persistence on some connections, so if connection was reset, it retries with an exponential backoff. Sometimes it runs without issues and sometimes it eats a lot of memory and even becomes unresponsive and is getting killed by watchdog. Apart from maintaining connections, my script just reads incoming data and writes it into a file, so there are no memory leaks in my code.
After a research, I found that timed out connections produce a lot of garbage, that can be cleaned only with GC. Here is a test scenario:
```php
$loop = React\EventLoop\Factory::create();
$loop->addPeriodicTimer(1, function () use ($loop) {
$connector = new \React\Socket\Connector($loop, array(
'timeout' => 0.5,
'dns' => false,
'tls' => …
```
=> Reduce memory consumption for failed connections

README.md, composer.json, src/Connection.php, tests/FunctionalSecureServerTest.php
PHP < 7.1.4 (and PHP < 7.0.18) suffers from a bug when writing big chunks of data over TLS streams at once. We try to work around this by limiting the write chunk size to 8192 bytes for older PHP versions only. This is only a work-around and has a noticable performance penalty on affected versions. Please update your PHP version.
Closes / resolves #105
=> Work around write chunk size for TLS streams for PHP < 7.1.4

README.md, src/FixedUriConnector.php, tests/FixedUriConnectorTest.php
The `FixedUriConnector` class implements the
[`ConnectorInterface`](#connectorinterface) and decorates an existing Connector
to always use a fixed, preconfigured URI.
This can be useful for consumers that do not support certain URIs, such as
when you want to explicitly connect to a Unix domain socket (UDS) path
instead of connecting to a default address assumed by an higher-level API:
```php
$connector = new FixedUriConnector(
'unix:///var/run/docker.sock',
new UnixConnector($loop)
);
// destination will be ignored, actually connects to Unix domain socket
$promise = $connector->connect('localhost:80');
```
Required to bring Unix domain socket (UDS) path support to our HttpClient (https://github.com/reactphp/http-client/issues/46)
Supersedes …
=> Add FixedUriConnector decorator to use fixed, preconfigured URI instead

src/Connection.php
This is an improvement over https://github.com/reactphp/socket/issues/92 that handles the new OSX-specific failure introduced by the initial fix for https://bugs.php.net/bug.php?id=74556.
=> Fix Unix domain socket (UDS) paths for Mac OS X

composer.json, tests/DnsConnectorTest.php, tests/LimitingServerTest.php, tests/SecureConnectorTest.php, tests/SecureServerTest.php, tests/TcpConnectorTest.php, tests/TestCase.php, tests/TimeoutConnectorTest.php, tests/UnixConnectorTest.php
Gets rid of the warnings and speeds up testing some.
Builds on top of #57
=> Forward compatibility with PHPUnit v5

composer.json, tests/FunctionalConnectorTest.php, tests/IntegrationTest.php, tests/TcpConnectorTest.php, tests/TcpServerTest.php, tests/UnixConnectorTest.php
This fixes a small oversight from #104: The test suite still used the deprecated `tick()` method which will be removed in the upcoming EventLoop release.
Builds on top of #104
=> Fix forward compatibility with upcoming EventLoop releases in tests

src/SecureServer.php, tests/SecureServerTest.php
This simple PR fixes a minor bug where a closed secure TLS server returned an empty string URI instead of a `null` value as documented. This also cherry-picks some minimal changes from @the-eater from #128 to make the tests less misleading (this was a small oversight from #98).
Supersedes / closes #128
=> Fix SecureServer to return null URI if server socket is already closed 

.travis.yml, tests/FunctionalSecureServerTest.php, tests/FunctionalTcpServerTest.php
Squashed by @clue, originally from reactphp/socket#124
~~~Marking this as WIP for now until tests are less flaky and outstanding test failures have been resolved.~~~
Resolves / closes #121
=> Test Mac OS X on Travis

.travis.yml
Builds on top of #130
Refs #109
=> Ignore Mac OS X test failures for now until Travis tests work again

README.md, examples/01-echo.php, examples/02-chat-server.php, examples/03-benchmark.php, src/Server.php, src/UnixServer.php, tests/ServerTest.php, tests/UnixServerTest.php
~~~Draft implementation for https://github.com/reactphp/socket/issues/25, tests still missing~~~
Resolves / closes #25
=> Support Unix domain socket (UDS) server

composer.json, tests/IntegrationTest.php, tests/SecureIntegrationTest.php, tests/ServerTest.php, tests/TcpConnectorTest.php, tests/TcpServerTest.php, tests/TestCase.php, tests/UnixServerTest.php
I use the `PHPUnit\Framework\TestCase` notation instead of `PHPUnit_Framework_TestCase` while extending our TestCase. This will help us migrate to PHPUnit 6, that [no longer support snake case class names](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).
I just need to bump PHPUnit version to [`^4.8.35`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.8.md#4835---2017-02-06) and [`^5.7`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-5.7.md#570---2016-12-02), that support this namespace.
=> Forward compatibility with PHPUnit 6

src/Connection.php, tests/ConnectionTest.php, tests/TcpConnectorTest.php
Currently, this component implicitly calls `fclose()` on the underlying socket resource before actually closing the stream (and removing it from the event loop). This code is in place ever since #99 has been merged, but the error didn't really manifest itself until recently, when https://github.com/reactphp/stream/pull/121 landed.
This issue can easily be reproduced by using latest react/stream with `ext-event` installed. If you have outgoing data pending on a connection, but the connection is detected to be closed by the remote peer, this would cause an uncaught exception.
This PR ensures we do not call `fclose()` on the socket resource prior to actually invoking the close logic and removing it from the event loop. I've added some tests to try to highlight this issue to avoid any future …
=> Fix closing socket resource before removing from loop

README.md, src/LimitingServer.php
=> Fixed typo.

.travis.yml, README.md, composer.json, src/Connector.php
This simple PR updates the DNS dependency to take advantage of the new config loader to apply the system default DNS config on all supported platforms. The previous default DNS server `8.8.8.8` will only be used as a fallback if no other DNS server could be found.
Also, this PR targets https://github.com/reactphp/dns/pull/96 which removed the dependency from react/dns to react/socket, which in turn depends on react/dns again. By removing this cyclic dependency, we can ensure Composer will automatically and correctly pick the latest installed version without having to specify the root package version. This change includes documentation updates and effectively reverts (the bad) parts of #54.
Resolves / closes #90 
Refs https://github.com/reactphp/dns/pull/93
Refs …
=> Update DNS dependency and load system default DNS config on all supported platforms

src/TcpConnector.php
While debugging some very odd memory issues in a live application, I noticed that this component shows some unexpected memory consumption and memory would not immediately be freed as expected when a connection attempt is cancelled. Let's not call this a "memory leak", because memory was eventually freed, but this clearly caused some unexpected and significant memory growth.
One of the core issues has been located and addressed via https://github.com/reactphp/event-loop/pull/164, but even with that patch applied, cancelling a pending connection attempt behaved a bit unexpected.
I've used the following script to demonstrate unreasonable memory growth:
```php
<?php
use React\EventLoop\Factory;
use React\Socket\Connector;
require __DIR__ . '/../vendor/autoload.php';
$loop = Factory::create(); …
```
=> Improve memory consumption for cancelled connection attempts

composer.json, src/TcpConnector.php, tests/IntegrationTest.php
While debugging some very odd memory issues in a live application, I noticed that this component shows some unexpected memory consumption and memory would not immediately be freed as expected. Let's not call this a "memory leak", because memory was eventually freed, but this clearly caused some unexpected and significant memory growth.
Parts of this issue have been resolved with #159 already which raised the discussion to address these issues in the upstream react/promise component. A number of patches have been filed via https://github.com/reactphp/promise/pull/113, https://github.com/reactphp/promise/pull/115, https://github.com/reactphp/promise/pull/116, https://github.com/reactphp/promise/pull/117, https://github.com/reactphp/promise/pull/118 and …
=> Improve memory consumption for failed connection attempts

README.md, src/UnixServer.php, tests/ServerTest.php, tests/UnixServerTest.php
PHP does not seem to report errno/errstr for Unix domain sockets (UDS) right now. This only applies to UDS server sockets, see also https://3v4l.org/NAhpr. Let's parse PHP warning message containing unknown error, HHVM reports proper info at least.
=> Improve Unix domain socket (UDS) server error messages

src/TcpConnector.php, tests/TcpConnectorTest.php
This simple PR improves TCP/IP error messages for failed and cancelled connection attempts slightly. In particular, the Exception message now always consistently includes the connection target URI.
Refs #168, #169 and #170
=> Improve TCP/IP error messages

src/TimeoutConnector.php, tests/DnsConnectorTest.php, tests/IntegrationTest.php, tests/TimeoutConnectorTest.php
This simple PR improves timeout error messages for failed and cancelled connection attempts slightly. In particular, the Exception message now always consistently includes the connection target URI.
Refs #168, #169, #170 and #171
=> Improve timeout error messages

src/StreamEncryption.php, tests/FunctionalSecureServerTest.php
PHP does not seem to report any warning message when the connection is lost (closed by the remote side) during a TLS handshake (both client and server side). As a result of this, the previous message appeared to be cut off. This PR ensures we indicate this error with proper errno/errstr.
Refs #168
=> Improve TLS error messages (Connection lost during TLS handshake)

src/SecureConnector.php, src/SecureServer.php, src/StreamEncryption.php, tests/FunctionalSecureServerTest.php, tests/IntegrationTest.php, tests/SecureConnectorTest.php
This PR improves TLS error messages (if connector fails due to TLS handshake errors) and improves (fixes) cancellation forwarding after the TCP/IP connection. This ensures that cancelling a pending connection attempt will properly cancel the underlying TCP/IP connection attempt and/or the TLS handshake.
The cancellation forwarding will eventually also be addressed upstream via reactphp/promise#99, but it's currently not decided when this version will be tagged. In the meantime, this PR works around this issue and improves cancellation semantics somewhat.
Refs #168, #169, #170, #171 and #176
=> Improve TLS error messages and cancellation forwarding during TLS handshake after TCP/IP connection

tests/FunctionalSecureServerTest.php
Using this dedicated assertion, we can have better error messages:
```diff
-$this->assertTrue($error instanceof \RuntimeException); // Failed asserting that false is true.
+$this->assertInstanceOf(\RuntimeException::class, $error); // Failed asserting that an object is an instance of class "RuntimeException".
```
=> Use dedicated assertInstanceOf assertion

tests/FunctionalSecureServerTest.php
This PR improves the test suite to avoid some possible race conditions for our TLS tests. It does not change anything about the actual behavior or the expected output, but it helps making the expected output more explicit and no longer subject to a possible race condition. Besides avoiding possible false negatives, this is also a prerequisite for the upcoming changes to bring in TLS 1.3 support via #184.
=> Improve test suite to avoid some possible race conditions

src/Connection.php, src/Connector.php, src/DnsConnector.php, src/LimitingServer.php, src/SecureConnector.php, src/SecureServer.php, src/Server.php, src/StreamEncryption.php, src/TcpConnector.php, src/TcpServer.php, src/UnixConnector.php, src/UnixServer.php
Just as previous PR's like https://github.com/reactphp/stream/pull/137 this prefixes all global functions and constants with a `\` to gain a small performance boost
=> Improve performance by prefixing all global functions calls with \ to skip the look up and resolve process and go straight to the global function

README.md, composer.json, src/Connection.php, src/StreamEncryption.php, tests/FunctionalSecureServerTest.php
TLS 1.3 is now an official standard as of August 2018 (https://tools.ietf.org/html/rfc8446) which is great news! :tada: See https://wiki.openssl.org/index.php/TLS1.3 if you want to learn more about why this is great news.
OpenSSL 1.1.1 supports TLS 1.3 (https://www.openssl.org/blog/blog/2017/05/04/tlsv1.3/). For example, this version ships with Ubuntu 18.10 (and newer) by default, meaning that recent installations support TLS 1.3 out of the box :shipit:
At the time of writing this, PHP does not know about TLS 1.3 at all. Interestingly, due to the way how PHP interfaces with OpenSSL, this means that TLS 1.3 is in fact enabled by default for all client and server connections when using a recent OpenSSL version (see also #184 for more details).
This PR improves TLS 1.3 support by working …
=> Improve TLS 1.3 support

src/SecureServer.php, tests/SecureServerTest.php
This fixes a race condition where the remote address could appear to be
"emtpy" in the server exception message, that could occur when the
connection to the peer was already closed during the TLS handshake. This
is simply avoided by getting the remote address prior to starting the
TLS handshake, in which case the remote address is known to exist.
Builds on top of #185, discovered while working on #186
=> Avoid possibility of missing remote address when TLS handshake fails

tests/FunctionalSecureServerTest.php, tests/SecureIntegrationTest.php, tests/TestCase.php
This PR improves the test suite to avoid a possible race condition for
our TLS tests. It does not change anything about the actual behavior or
the expected output, but it helps making the expected output more
explicit and no longer subject to a possible race condition. This helps
avoiding possible false negatives if TLS 1.3 is supported and PHP
reports the EOF indicator before consuming all application data.
This builds on top of https://github.com/reactphp/socket/pull/185 and https://github.com/reactphp/socket/pull/186
=> Work around failing test case detecting EOF on TLS 1.3 socket streams

README.md, src/Connection.php
The work around was introduced in order to bring TLS 1.3 support to all
supported versions, but at the same time it may cause very large data
chunks for high throughput scenarios. The underlying bug has been fixed
in PHP 7.3.3 and PHP 7.2.15, so we can avoid this now uneeded work
around on said version.
Reproduction is not exactly trivial unfortunately. Prior to #186, older PHP version would simply consume 100% CPU usage when using an otherwise perfectly valid TLS 1.3 connection when the remote peer did not send any data (common for HTTPS). After applying #186 this bug has been avoided on all supported versions, including older PHP versions. However, at the same time it may cause very large data chunks for high throughput scenarios. In other words, when downloading large files over HTTPS, …
=> Avoid uneeded fragmented TLS work around for PHP 7.3.3+

README.md, composer.json, src/Connector.php, src/DnsConnector.php, tests/ConnectorTest.php, tests/DnsConnectorTest.php
As of https://github.com/reactphp/dns/pull/134, all DNS classes are marked as `final`, including the `Resolver` class which is most commonly used in consuming packages. This changeset adjusts our connectors to accept the `ResolverInterface` interface as the common interface into this class and also adjust tests to use this interface for mocking. This is not a BC break because the interface is strictly compatible with the original `Resolver` behavior.
Resolves https://github.com/reactphp/socket/issues/207
Builds on top of https://github.com/reactphp/dns/pull/139 and https://github.com/reactphp/dns/pull/134
=> Accept DNS `ResolverInterface` and fix failing test suite

tests/IntegrationTest.php
This simple changeset avoids a failing test by now using an invalid DNS resolver IP instead of an invalid hostname.
Refs https://github.com/reactphp/dns/pull/146
=> Avoid failing test by using invalid DNS resolver IP instead of hostname

README.md, src/HappyEyeBallsConnectionBuilder.php, src/HappyEyeBallsConnector.php, tests/HappyEyeBallsConnectorTest.php, tests/TestCase.php, tests/TimerSpeedUpEventLoop.php
By using the happy eye balls algorythm as descripted in [`RFC6555`](https://tools.ietf.org/html/rfc6555) and
[`RFC8305`](https://tools.ietf.org/html/rfc8305) it will connect to the quickest responding server with a
preference for IPv6.
=> Implement the Happy Eye Balls RFC's

tests/FunctionalSecureServerTest.php
Explicit TLS 1.3 support will be available in PHP 7.4: https://github.com/php/php-src/pull/3909
Older PHP versions implicitly support TLS 1.3 provided that the
underlying OpenSSL version supports TLS 1.3. However, for PHP 7.3 some
(not so) recent changes implicitly disable TLS 1.3, so we skip TLS 1.3 tests on
affected PHP versions: https://github.com/php/php-src/pull/3317
Builds on top of #186, #201 and #202
Noticed this due to a build error while working on https://github.com/reactphp/reactphp/pull/432
=> Improve test suite to exclude TLS 1.3 tests on PHP 7.3

src/TcpServer.php
To be strict, the second parameter of this function is a `bool` instead of an `int`.
=> Minor code style fix for stream_set_blocking() parameter type

.travis.yml, composer.json, phpunit.xml.dist, tests/DnsConnectorTest.php, tests/IntegrationTest.php, tests/SecureConnectorTest.php, tests/TcpConnectorTest.php
Builds on top of reactphp/dns#156, reactphp/promise#162 and reactphp/event-loop#209
=> Run tests on PHP 7.4 and simplify test matrix

README.md, composer.json, src/Connector.php, src/HappyEyeBallsConnectionBuilder.php, tests/ConnectorTest.php, tests/FunctionalConnectorTest.php, tests/HappyEyeBallsConnectionBuilderTest.php, tests/IntegrationTest.php
The `Connector` class now defaults to using the
[happy eyeballs algorithm](https://en.wikipedia.org/wiki/Happy_Eyeballs) to
automatically connect over IPv4 or IPv6 when a hostname is given.
This automatically attempts to connect using both IPv4 and IPv6 at the same time
(preferring IPv6), thus avoiding the usual problems faced by users with imperfect
IPv6 connections or setups.
If you want to revert to the old behavior of only doing an IPv4 lookup and
only attempt a single IPv4 connection, you can set up the `Connector` like this:
```php
$connector = new React\Socket\Connector($loop, array(
'happy_eyeballs' => false
));
```
Supersedes / closes #216, thanks @WyriHaximus for the original version. On top of this, I've resolved a garbage reference in legacy PHP by avoiding some unneeded …
=> Make happy eyeballs algorithm (IPv6) the default, add new `happy_eyeballs` option to `Connector`

composer.json, src/HappyEyeBallsConnectionBuilder.php, tests/FunctionalConnectorTest.php, tests/HappyEyeBallsConnectionBuilderTest.php, tests/HappyEyeBallsConnectorTest.php
This changeset fixes a leftover timer reference when cancelling the happy eyeballs connection attempt. Additionally, this increases test coverage to 100% and significantly improves test times (27s->5s).
Builds on top of #224
=> Fix cancelling happy eyeballs to stop timer, fix rejection reason and simplify timer logic

src/Connector.php, tests/FunctionalConnectorTest.php
Resolves / closes #115
Builds on top of https://github.com/reactphp/dns/pull/127 and https://github.com/reactphp/cache/pull/26
=> Default to using DNS cache (with max 256 entries) for Connector

tests/FunctionalSecureServerTest.php
Skip legacy TLS 1.0 / TLS 1.1 tests if disabled by system. For example, this affects a current Ubuntu 20.04 installation which appears to prohibit legacy TLS connections.
The same bug can be reproduced in curl with `$ curl -s --tlsv1 -v https://tls-v1-0.badssl.com:1010/` at the time of writing this. This seems to be addressed in curl with https://github.com/curl/curl/issues/4097 and https://github.com/curl/curl/pull/4304. PHP appears to apply a similar logic, but it still fails at the moment (https://github.com/php/php-src/blob/8e9bc90004f09a0d67fdac393a8f3fca904be397/ext/openssl/xp_ssl.c#L1760 vs https://github.com/ruby/openssl/blob/4b43ffc1292eeb70ff886847836e21ad96ed8796/ext/openssl/ossl_ssl.c#L162-L195).
For PHP, this can be reproduced (prior to applying this patch) by running the …
=> Skip legacy TLS 1.0 / TLS 1.1 tests if disabled by system

src/HappyEyeBallsConnectionBuilder.php, tests/HappyEyeBallsConnectionBuilderTest.php, tests/HappyEyeBallsConnectorTest.php
Improve error reporting when DNS lookup fails (happy eyeballs). The rejection message now always contains the underlying DNS error message with more details.
Also fixes a fatal error with legacy PHP 5 where it would fail with a
(catchable) fatal error when either DNS lookup fails. During test runs,
this would automatically be turned into an Exception and would
successfully reject the promise. Without an appropriate error handler, a
soft DNS error (such as when IPv6 is not available) would previously
terminate the program with a fatal error.
Builds on top of #224 and #225
Refs #171 and others
=> Improve error reporting when DNS lookup fails (happy eyeballs)

src/HappyEyeBallsConnectionBuilder.php, tests/HappyEyeBallsConnectionBuilderTest.php, tests/HappyEyeBallsConnectorTest.php
Improve error reporting when TCP/IP connection fails (happy eyeballs). The rejection message now always contains the underlying TCP/IP error message with more details.
Additionally, improve timer logic for next attempt timer and fix leftover timer reference.
Use one-off timers that will be scheduled only when a following
connection attempt should be started instead of using a dangling
periodic timer that could possibly keep running even when no connection
attempts are scheduled anymore.
Builds on top of #230, #224 and #225
Refs #171 and others
=> Improve error reporting when TCP/IP connection fails (happy eyeballs) 

src/HappyEyeBallsConnectionBuilder.php, tests/HappyEyeBallsConnectionBuilderTest.php, tests/HappyEyeBallsConnectorTest.php
This changeset ensures a new connection attempt will be started immediately when one connection attempt fails. This is quite common when connecting on IPv4-only systems where the first IPv6 connection will fail and the next connection attempt should not have to wait 100ms.
The 100ms delay between connection attempts now only triggers when the connection attempt is still pending. Afaict this is not in violation of RFC 8305 and seems to be in line with how other implementations handle this specific situation (https://daniel.haxx.se/blog/2020/03/16/curl-ootw-happy-eyeballs-timeout/, https://www.isc.org/blogs/2011-01-19-multi-homed-server-over-tcp/, https://github.com/curl/curl/issues/2281 and others).
This can easily be reproduced by connecting to `localhost:1` when nothing is listening on …
=> Immediately try next connection when one attempt fails and fix possible race conditions (happy eyeballs)

src/HappyEyeBallsConnectionBuilder.php, tests/HappyEyeBallsConnectionBuilderTest.php, tests/HappyEyeBallsConnectorTest.php
This changeset improves error reporting for failed connection attempts using happy eyeballs to always include the last error message for both IPv6 and IPv4 protocol families. The rationale for this is that both families commonly fail for very different reasons (broken IPv6 connectivity etc.). If both families report the same error, the message will only include a single message:
```php
Connection to foo.invalid failed during DNS lookup: DNS query for foo.invalid returned an error response (Server Failure)
Connection to asdasd.com failed: Last error for IPv4: Given URI "tcp://127.0.0.1?hostname=asdasd.com" is invalid. Previous error for IPv6: DNS query for asdasd.com did not return a valid answer (NOERROR / NODATA)
```
Builds on top of #232, #231, #230, #224 and #225
Refs #171 and others
=> Improve error reporting to include both IPv6 & IPv4 errors (happy eyeballs)

src/Connection.php, src/StreamEncryption.php, src/TcpConnector.php, src/TcpServer.php, tests/ServerTest.php, tests/TcpConnectorTest.php, tests/TcpServerTest.php, tests/UnixServerTest.php
=> Minor code cleanup, remove dead code and improve code coverage to 100%

.travis.yml, tests/FunctionalConnectorTest.php, tests/FunctionalSecureServerTest.php, tests/IntegrationTest.php, tests/SecureConnectorTest.php, tests/SecureIntegrationTest.php, tests/SecureServerTest.php, tests/ServerTest.php, tests/TcpConnectorTest.php
Builds on top of #223, https://github.com/reactphp/stream/pull/150 and others.
=> Simplify Travis CI test matrix for Mac OS X setup and skip all TLS tests on legacy HHVM

src/StreamEncryption.php, tests/FunctionalConnectorTest.php
This changeset fixes closing the pending connection attempt when the connection is cancelled during the TLS handshake. This is a minor oversight from the previous cleanup in https://github.com/reactphp/socket/commit/15426bdcb905511915ec2784448e32f08375d45b#diff-fa535a0ca5a2f2df7b368c67e3bfd18dL66. This is now covered by some higher level integration tests to ensure correct system behavior.
=> Fix closing connection when cancelling during TLS handshake

README.md, src/TcpServer.php, tests/FunctionalTcpServerTest.php
The `backlog` parameter used to default to just 32 as of PHP 5.3.3 and
used to be hard coded to 4 in earlier PHP versions.
The new default of 511 was evaluated to be a reasonable value for
event-driven applications that can cope with many concurrent connections
on a variety of platforms. In particular, this solves common ECONNRESET
(connection reset by peer) errors when running benchmarks with higher
concurrency. For more specific requirements, the `backlog` parameter can
be given explicitly to override this default.
See https://github.com/php/php-src/commit/5b277c4da0d9fb8bfb59186b61a884aaafffb861
Refs https://github.com/reactphp/http/issues/354 and others
=> Change default socket backlog size to 511

.gitattributes, .travis.yml, composer.json, phpunit.xml.dist, phpunit.xml.legacy, tests/HappyEyeBallsConnectionBuilderTest.php, tests/HappyEyeBallsConnectorTest.php
PHPUnit 9.3 released a new schema for the `phpunit.xml` configuration file. I had to migrate the file to the new format in order to avoid the warning. PHPUnit Versions older than 9.3 have to use the `phpunit.xml.legacy` configuration file, because the new format is unknown for them.
I also had to update  some tests, because the `at()` matcher deprecated in PHPUnit 9.3 and will be removed in PHPUnit 10.
The code needs some minor changes to run with PHP 8, I will look into this in an upcoming pull request.
For further details concerning this pull request look into [graphp/graphviz #46](https://github.com/graphp/graphviz/pull/46).
This pull request builds on top of [reactphp/socket #239](https://github.com/reactphp/socket/pull/239).
=> Update PHPUnit configuration schema for PHPUnit 9.3 and replace deprecated at() Mocks

src/TcpServer.php, src/UnixServer.php, tests/TcpServerTest.php, tests/UnixServerTest.php
Multiple socket servers can listen on the same socket address (using
`SO_REUSEPORT` or shared file descriptors). Accordingly, when a new
connection is incoming, multiple event-loops could report the socket to
be readable and try to a `accept()` an incoming connection from the same
socket.
This wouldn't be an issue with the underlying `accept()` system call.
The first call would succeed and subsequent calls would report `EAGAIN`
or `EWOULDBLOCK` for the other servers given the socket resource is in
non-blocking mode.
However, PHP's `stream_socket_accept()` implementation first runs a
`poll()` on the socket resource before performing an `accept()`. This
means multiple instances listening on the same address could end up in a
race condition where some may be "stuck" in the pending `poll()`. …
=> Fix possible `accept()` race condition when multiple socket servers listen on same socket address

src/Connection.php
The previous code works just fine on PHP 7 and older. PHP 8 adds
stricter type checks for closed socket resources, so the underlying
function now throws a `TypeError`. This can be avoided by first checking
if the socket resource is still valid (not closed). This works across
all PHP versions and also helps with avoiding some uneeded error
suppression operators.
This means this component now supports PHP 8 just fine :tada: 
```bash
~/workspace/reactphp-socket$ docker run -it --rm -v `pwd`:/data --workdir /data php:8.0.0beta1-cli php -d memory_limit=-1 vendor/bin/phpunit                                          
PHPUnit 9.3.7 by Sebastian Bergmann and contributors. …
```
=> Socket address of closed socket should be null (support PHP 8)

src/HappyEyeBallsConnectionBuilder.php, tests/HappyEyeBallsConnectionBuilderTest.php, tests/HappyEyeBallsConnectorTest.php
The happy eyeballs algorithms tries to connect over both IPv6 and IPv4
at the same time. Accordingly, the hostname has to be resolved for both
address families which both may potentially contain any number of
records (load balancing).
This changeset randomizes the order of returned IP addresses per address
family. This means that if multiple records are returned, it will try to
connect to a random one from this list instead of always trying the
first. This allows the load to be distributed more evenly across all
returned IP addresses. This can be used as a very basic DNS load
balancing mechanism.
This is similar to what the old `DnsConnector` did (it always tried one random IP from the list of IPs). See also https://daniel.haxx.se/blog/2012/01/03/getaddrinfo-with-round-robin-dns-and-happy- …
=> Use round robin for happy eyeballs DNS responses (load balancing)

src/HappyEyeBallsConnectionBuilder.php, tests/HappyEyeBallsConnectionBuilderTest.php
This changeset applies some internal improvements to avoid unhandled rejection for future Promise API. This does not affect current behavior in any way (test cases are unaffected), but makes sure we do not use any unhandled promise rejections anymore. As discussed in https://github.com/reactphp/promise/issues/87 this could otherwise raise some error/warning in future.
Resolves / closes #248
Refs #214
=> Internal improvement to avoid unhandled rejection for future Promise API

composer.json, src/Connector.php
This changeset adds support for falling back to multiple DNS servers from DNS config. In other words, if you have multiple DNS servers configured (rare) and connectivity to the primary DNS server is broken (even rarer), it will now fall back to your other DNS servers.
This is done by simply passing the complete list of DNS servers down to the DNS component that is responsible for setting up the DNS executor stack. Accordingly, this builds on top of https://github.com/reactphp/dns/pull/179 and https://github.com/reactphp/dns/pull/180.
=> Support falling back to multiple DNS servers from DNS config

README.md, examples/01-echo-server.php, examples/02-chat-server.php, examples/03-http-server.php, examples/91-benchmark-server.php, src/ServerInterface.php, src/SocketServer.php, tests/SocketServerTest.php
This changeset adds a new `SocketServer` class as a replacement for the `Server` class to avoid class name collisions and ambiguities.
```php
// deprecated
$socket = new React\Socket\Server(0);
$socket = new React\Socket\Server('127.0.0.1:8000');
$socket = new React\Socket\Server('127.0.0.1:8000', null, $context);
$socket = new React\Socket\Server('127.0.0.1:8000', $loop, $context);
// new
$socket = new React\Socket\SocketServer('127.0.0.1:0');
$socket = new React\Socket\SocketServer('127.0.0.1:8000');
$socket = new React\Socket\SocketServer('127.0.0.1:8000', $context);
$socket = new React\Socket\SocketServer('127.0.0.1:8000', $context, $loop);
```
The new `SocketServer` class has been added with an improved constructor signature as a replacement for the previous `Server` class in order …
=> Add new `SocketServer` and deprecate `Server` to avoid class name collisions

src/TcpConnector.php, tests/TcpConnectorTest.php
This changeset improves the error messages for failed TCP/IP connections to include the appropriate errno/errstr. Whereas it would previously report a generic "Connection refused" error, it will now report the actual underlying error condition, such as this:
```bash
$ telnet 192.168.0.1 8080
Trying 192.168.0.1...
telnet: Unable to connect to remote host: Network is unreachable
$ php examples/11-http-client.php 192.168.0.1
RuntimeException: Connection to tcp://192.168.0.1:80 failed: Network is unreachable in …/TcpConnector.php:115
```
Builds on top of #171 and others
=> Improve error messages for failed TCP/IP connections with errno/errstr

src/TcpConnector.php, tests/TcpConnectorTest.php
This changeset improves error messages for failed TCP/IP connections when `ext-sockets` is not available on Linux. This means it will now consistently report errno/errstr on most supported platforms such as this:
```bash
$ telnet 192.168.0.1 8080
Trying 192.168.0.1...
telnet: Unable to connect to remote host: Network is unreachable
$ php examples/11-http-client.php 192.168.0.1
RuntimeException: Connection to tcp://192.168.0.1:80 failed: Network is unreachable in …/TcpConnector.php:115
```
Builds on top of #265, #171, reactphp/dns#171, reactphp/dns#172 and others
=> Improve error messages for failed TCP/IP connections without ext-sockets

src/SocketServer.php, src/TcpServer.php, src/UnixServer.php, tests/TcpServerTest.php, tests/UnixServerTest.php
This changeset improves the error messages for failed incoming connections to include the appropriate errno/errstr. Reporting the errstr works on all supported platforms, the errno is only available when `ext-sockets` is available. Whereas it would previously report a generic "Error accepting new connection" error, it will now report the actual underlying error condition, such as this:
```diff
-Error accepting new connection
+Failed to accept new connection: Connection timed out
```
Builds on top of #266, #265, #171, https://github.com/reactphp/dns/pull/171, https://github.com/reactphp/dns/pull/172 and others
Together with #244 this is a prerequisite for #164
=> Improve error messages when accepting connections with errno/errstr

tests/TcpServerTest.php, tests/UnixServerTest.php
The improved error messages in #267 by @clue are not supported under HHVM.
=> Skip unsupported tests for HHVM

README.md, examples/01-echo-server.php, examples/02-chat-server.php, examples/03-http-server.php, src/FdServer.php, src/SocketServer.php, tests/FdServerTest.php, tests/SocketServerTest.php
This changeset adds support for listening on existing file descriptors (FDs) with the `SocketServer`:
```php
$socket = new SocketSever('php://fd/3');
```
This is particularly useful when using systemd socket activation like this:
```bash
$ systemd-socket-activate -l 8000 php examples/03-http-server.php php://fd/3
```
See also https://www.freedesktop.org/software/systemd/man/systemd.socket.html and http://0pointer.de/blog/projects/socket-activation.html for details on systemd socket activation.
The implementation and test suite is pretty straight forward and somewhat similar to the existing `TcpServer` and `UnixServer` except for the constructor using `fopen('php://fd/3', 'r')` to duplicate an existing file descriptor instead of creating a new socket server. Most of the work went into …
=> Support listening on existing file descriptors (FDs) with `SocketServer`

README.md, examples/11-http-client.php, examples/12-https-client.php, examples/21-netcat-client.php, examples/22-http-client.php, src/Connector.php, src/DnsConnector.php, src/HappyEyeBallsConnectionBuilder.php, src/HappyEyeBallsConnector.php, src/SecureConnector.php, tests/DnsConnectorTest.php, tests/FunctionalConnectorTest.php, tests/HappyEyeBallsConnectionBuilderTest.php, tests/HappyEyeBallsConnectorTest.php, tests/SecureConnectorTest.php
This changeset improves error messages for failed connections. In particular, failed TCP/IP connections using the happy eyeballs connector (the default) or the old DNS connector will now report the hostname once at the beginning of the message and will not show its internal hostname parameter multiple times:
```diff
- Connection to tcp://localhost:80 failed: Last error for IPv4: Connection to tcp://127.0.0.1:80?hostname=localhost failed: Connection refused. Previous error for IPv6: Connection to tcp://[::1]:80?hostname=localhost failed: Connection refused
+ Connection to tcp://localhost:80 failed: Last error for IPv4: Connection to tcp://127.0.0.1:80 failed: Connection refused. Previous error for IPv6: Connection to tcp://[::1]:80 failed: Connection refused
```
Likewise, we now make sure …
=> Improve error messages for failed connections

src/DnsConnector.php, src/HappyEyeBallsConnector.php, src/TcpConnector.php, src/TcpServer.php, tests/FunctionalConnectorTest.php
This simple changeset avoids an unneeded (and undeclared!) dependency on `ext-filter`. The extension is enabled by default, but can explicitly be disabled with `--without-filter`.
The code in question is already covered by the test suite, so the test suite confirms this changeset does not affect behavior or our public API in any way. Accordingly, this is entirely transparent for all consumers of this package, plus now also supports consumers that happen use `--without-filter`.
The changes have been ported from https://github.com/reactphp/dns/pull/185
See https://www.php.net/manual/en/filter.installation.php
Originally reported in https://github.com/leproxy/leproxy/issues/80
Refs https://github.com/reactphp/socket/pull/17
=> Avoid dependency on `ext-filter`

tests/TcpConnectorTest.php
This changeset improves the test suite to skip the FD test when hitting the memory limit. This is particularly useful when testing systems with a low memory limit in place and Docker which defaults to a very large number of FDs, thus potentially requiring a lot of memory.
The changes have been ported from https://github.com/reactphp/child-process/pull/90
Builds on top of #236
Refs #277 and others
=> Improve test suite to skip FD test when hitting memory limit

composer.json, phpunit.xml.dist, src/DnsConnector.php, src/HappyEyeBallsConnector.php
This changeset adds support for PHP 8.1.
~~I'm marking this as WIP because it currently reports a deprecation notice that needs to be addressed upstream first (https://github.com/reactphp/promise-timer/pull/50). I'll update this PR once this version is released.~~
Builds on top of #274
Refs https://github.com/friends-of-reactphp/mysql/pull/150
=> Support PHP 8.1

tests/FunctionalSecureServerTest.php
Skip legacy TLS 1.0 tests if disabled by system. For example, this affects Fedora 36 installations which prohibit legacy TLS 1.0 connections by default. By today's standards, TLS 1.0 would be considered insecure, so it makes sense this is prohibited by default even if explicitly requested like in our test suite. Accordingly, this changeset only affects the test suite and has no effect on runtime.
For PHP, this can be reproduced (prior to applying this patch) by running the test suite in a default Fedora 36 installation like this:
```bash
$ docker run -it --rm -v `pwd`:/data --workdir=/data fedora:36 bash
```
Resolves / closes #275
Builds on top of #229
=> Skip legacy TLS 1.0 tests if disabled by system
